user = "joe"

arch_packages = [
  "alacritty",
  "deja-dup",
  "docker",
  "docker-compose",
  "gtk-layer-shell",
  "helix",
  "hyprland",
  "libreoffice",
  "nushell",
  "pamixer",
  "pass",
  "pulsemixer",
  "signal",
  "stow",
  "socat",
  "wl-clipboard",
  "zellij",
  "zenith"
]

eww_repo = "git@github.com:elkowar/eww.git"
swww_repo = "git@github.com:Horus645/swww.git"
dotfiles_repo = "git@github.com:JosephGonzalez03:{password}/.dotfiles.git"
font_url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/RobotoMono.zip"
